### ISSUE TITLE
Overwriting Header

### ISSUE THREAD

**Issue by schnittstabil** [mikicaivosevic/clickjacking-middleware#2]
>  Does not set the header if it's already set.

Is there any good reason for this? The following looks like a valid use case to me:

``` php
$app = new \Slim\App();

$app->group('/foo', function () {
    $this->get('/bar', function ($request, $response) {
    // ...
    })->add(new XFrameOptions('SAMEORIGIN'));

    $this->get('/bar2', function ($request, $response) {
    // ...
    });
})->add(new XFrameOptions('DENY'));
```

**Comment by mikicaivosevic** [comment]
Yea, it looks like a valid use case, I have merged :) Thanks

**Comment by schnittstabil** [comment]
Whoa whoa... PR #1 solves a different issue. If you don't mind, I'll create an new PR for this one.

**Comment by mikicaivosevic** [comment]
Sorry, I made mistake. but I agree with you, this is valid use case :) Thanks for contribution.
